pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'xuanhutong'

include 'common'
include 'gateway'
include 'auth-service'
include 'medical-service'
include 'clinic-service'
include 'prescription-service'
