plugins { id 'org.springframework.boot' }
dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.flywaydb:flyway-core'; implementation 'org.flywaydb:flyway-mysql'
    implementation 'com.google.zxing:core:3.5.3'; implementation 'com.google.zxing:javase:3.5.3'
}
